### ISSUE TITLE
Cannot use buffer key

### ISSUE THREAD

**Issue by maartenbreddels** [vidartf/ipydatawidgets#18]
Due to https://github.com/jupyter-widgets/ipywidgets/issues/1748 we cannot use the buffer key in a json object for sending from frontend to kernel.

**Comment by vidartf** [comment]
@maartenbreddels The discussion in the linked issue indicates that there might be something that can be done in ipywidgets to fix this. Is this so? If that is the case, I would prefer that solution over changing the serialization format here.

**Comment by maartenbreddels** [comment]
Absolutely, see https://github.com/jupyter-widgets/ipywidgets/issues/1748 I just wanted to make a note that it does not work currently.

**Comment by vidartf** [comment]
Going to leave this as it is, and rely on the upstream fix in https://github.com/jupyter-widgets/ipywidgets/pull/2205 .

**Comment by vidartf** [comment]
Note: I don't think this was ever an issue for ipydatawidgets since the value of the `buffer` key was always a view, and not an `ArrayBuffer`.

**Comment by vidartf** [comment]
(at least if the typings of the API were observed)
