### ISSUE TITLE
List or Tuple with NDArray entries

### ISSUE THREAD

**Issue by thewtex** [vidartf/ipydatawidgets#32]
@vidartf How is serialization specified on the Python and JavaScript side for a `List` or `Tuple` traitlet that can have `NDArray` entries?

**Comment by vidartf** [comment]
There is no pre-defined serializer for that at the moment. If you know that you will always have a list/tuple, and only one level deep (no nesting), it is quite straight forward to write your own ((de-)serializer is just a mapping call to the inner (de-)serializer). If you want to handle arbitrary nesting in both lists and dicts, things get a little more complicated (but still solvable).

**Comment by vidartf** [comment]
An arbitrary nesting serializer would be nice to have in the package though. The python ones could handle it by default, while the JS one could have a factory function called with which inner serializer function to use.

**Comment by thewtex** [comment]
@vidartf cool, thanks for the info. :+1: 

My current need is for a one level deep nesting, mixing NDArray's and `None` / `null` in a `List`. I will implement a custom serializer for that first and provide a link here (though this will not be immediate).

**Comment by vidartf** [comment]
Closing as answered/stale.
