### ISSUE TITLE
is ipydatawidgets compatible with Jupyterlab-1.0.0rc ?

### ISSUE THREAD

**Issue by stonebig** [vidartf/ipydatawidgets#33]

**Comment by vidartf** [comment]
Still waiting on core jupyter-widgets to release RC, then I will update it.

**Comment by stonebig** [comment]
and now ?

**Comment by vidartf** [comment]
Can you expand a bit on your question? I'm not sure what you are asking.

**Comment by stonebig** [comment]
Is ipydatawidgets compatible with current jupyterlab-1.2.6 ?

**Comment by vidartf** [comment]
It should be. Are you having issues?

**Comment by stonebig** [comment]
no, just checking i could close this

**Comment by vidartf** [comment]
Ah, thanks.
