### ISSUE TITLE
No provider for: jupyter.extensions.jupyterWidgetRegistry

### ISSUE THREAD

**Issue by LunarLanding** [vidartf/ipydatawidgets#35]
On running jupyterlab, the following error shows on the browser console:
`Plugin 'jupyter.extensions.datawidgets' failed to activate.`
`No provider for: jupyter.extensions.jupyterWidgetRegistry`

Environment:
node v12.7.0 
npm 6.10.2

[conda_list.txt](https://github.com/vidartf/ipydatawidgets/files/3444189/conda_list.txt)
[conda_list_explicit.txt](https://github.com/vidartf/ipydatawidgets/files/3444190/conda_list_explicit.txt)
[jupyter_lab_build.txt](https://github.com/vidartf/ipydatawidgets/files/3444222/jupyter_lab_build.txt)
[jupyterlab_labextension_list.txt](https://github.com/vidartf/ipydatawidgets/files/3444223/jupyterlab_labextension_list.txt)

I am coming here after encountering this issue with k3d which uses ipydatawidgets:
https://github.com/K3D-tools/K3D-jupyter/issues/178

**Comment by vidartf** [comment]
The lab build seems to have the relevant warnings:

```


    WARNING in @jupyter-widgets/base
      Multiple versions of @jupyter-widgets/base found:
        1.2.5 ./~/@jupyter-widgets\base from ./~/@jupyter-widgets\base\lib\index.js
        2.0.1 ./~/@jupyter-widgets\jupyterlab-manager/~/@jupyter-widgets\base from ./~/@jupyter-widgets\jupyterlab-manager/~/@jupyter-widgets\base\lib\index.js


    WARNING in d3-array
      Multiple versions of d3-array found:
        1.2.4 ./~/d3-scale/~/d3-array from ./~/d3-scale/~/d3-array\src\index.js
        2.2.0 ./~/d3-array from ./~/d3-array\src\index.js


    WARNING in jupyter-dataserializers
      Multiple versions of jupyter-dataserializers found:
        1.3.1 ./~/jupyter-dataserializers from ./~/jupyter-dataserializers\lib\index.js
        2.1.0 ./~/jupyter-datawidgets/~/jupyter-dataserializers from ./~/jupyter-datawidgets/~/jupyter-dataserializers\lib\ndarray.js
```

It seems K3D has not yet added support for jupyterlab 1.0
