### ISSUE TITLE
npmjs.com GitHub links + naming npm package folders

### ISSUE THREAD

**Issue by consideRatio** [vidartf/ipydatawidgets#37]
## Reference this GitHub repo from the NPM packages

Adding links back here from the NPM package would help past me and future me, even though I got it right now =)

https://www.npmjs.com/package/jupyter-dataserializers
https://www.npmjs.com/package/jupyter-datawidgets
https://www.npmjs.com/package/jupyterlab-datawidgets (got links, but they are broken)

## Rename folders
Also, it would be very helpful to have a naming in the https://github.com/vidartf/ipydatawidgets/tree/master/packages folder that matches these NPM package names. It took quite a while for me to figure out that there are jupyter-datawidgets AND jupyterlab-datawidgets, but it would had been obvious if there were two folders next to each other with different names.

`serializers` -> `jupyter-dataserializers`
`jupyter-datawidgets` -> `jupyter-datawidgets` (no change)
`jlabextension` -> `jupyterlab-datawidgets`

**Comment by vidartf** [comment]
For the links, yes that would be nice. If you want to do a PR, that will help :)

For the renaming, I kind of agree, but having multiple folders with the same prefix is just annoying w.r.t. tab completion of folder names 🤷‍♂

**Comment by consideRatio** [comment]
@vidartf ah but I cannot change the npmjs.com provided information, at least I don't think so, or ? Is that something you set in package.json?! Ah!

**Comment by consideRatio** [comment]
Closing as no longer relevant as jupyterlab 3 makes npm packages obsolete
